[package]
name = "ncurses_menu_lib"
version = "0.1.0"
authors = ["protobit <admin@protobyte.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pancurses="0.16.1"